version: "3"
services:
  docker_node:
    container_name: conteneur_node
    build: .
    image: node
    working_dir: /app
    volumes:
      - .:/app
      - ./test:/test_discord_docker
    ports:
      - 4200:3000
    command: bash -c "npm install discord.js && npm i -D chai mocha  && npm i -D @types/chai @types/mocha && ts-node "